### ISSUE TITLE
Hosting pretrained models on Hugging Face

### ISSUE THREAD

**Issue by merveenoyan** [miccunifi/KDPL#2]
Hello @marcomistretta  🤗

I'm Merve and I work on computer vision at Hugging Face. I see your paper is accepted, congratulations on getting accepted to ECCV!
I see you claimed your paper here https://huggingface.co/papers/2407.03056. The paper page lets people discuss about your paper and lets them find artifacts about it, you can also claim the paper as yours which will show up on your public profile at HF.

Would you like to host the models you pre-trained with this technique on https://huggingface.co/models? I couldn't find the models. If you'd like to, hosting on Hugging Face will give your work more visibility.

Leaving a guide [here](https://huggingface.co/docs/hub/models-uploading). If it's a PyTorch model, you can use [PyTorchModelHubMixin](https://huggingface.co/docs/huggingface_hub/package_reference/mixins#huggingface_hub.PyTorchModelHubMixin) class which adds from_pretrained and push_to_hub to the model which lets you to upload the model and people to download and use models right away.
If you do not want this and directly want to upload model through UI or however you want, people can also use [hf_hub_download](https://huggingface.co/docs/huggingface_hub/en/guides/download#download-a-single-file).

What do you think?

**Comment by marcomistretta** [comment]
Hi @merveenoyan 🤗,

Thanks for reaching out! 
I’d love to host the models on Hugging Face, but at the moment, I'm quite busy preparing for ICLR🤞
I'll definitely get to it when I have some free time!

Appreciate the guide and I'll make sure to refer to it when I get the chance

Best,
Marco

**Comment by vatsalag99** [comment]
Hi! I wanted to ask if you had a chance to upload the pre-trained prompt weights on Huggingface or another storage platform? Thanks!
